In [1]:
import pandas as pd

df = pd.read_csv("new_dataset.csv")
df_test = pd.read_csv("new_test.csv")

numeric_df = df.select_dtypes(include=['int64', 'float64'])
numeric_df_test = df_test.select_dtypes(include=['int64', 'float64'])

correlation_matrix = numeric_df.corr()

high_corr_features = numeric_df.columns[correlation_matrix['SalePrice'].abs() > 0.7]

new_df = df[high_corr_features]
high_corr_features = high_corr_features.drop('SalePrice')
new_df_test = df_test[high_corr_features]

new_df

      OverallQual  GrLivArea  SalePrice
0               7       1710     208500
1               6       1262     181500
2               7       1786     223500
3               7       1717     140000
4               8       2198     250000
...           ...        ...        ...
1455            6       1647     175000
1456            6       2073     210000
1457            7       2340     266500
1458            5       1078     142125
1459            5       1256     147500

[1460 rows x 3 columns]

In [2]:
import numpy as np

# Вычисление среднего и стандартного отклонения
mean_price = new_df['SalePrice'].mean()
std_price = new_df['SalePrice'].std()
# Определение верхней и нижней границы для выбросов
lower_bound = mean_price - 2 * std_price
upper_bound = mean_price + 2* std_price

import numpy as np

# # Замена выбросов на значения в пределах границ
new_df.loc[new_df['SalePrice'] < lower_bound, 'SalePrice'] = lower_bound
new_df.loc[new_df['SalePrice'] > upper_bound, 'SalePrice'] = upper_bound

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error



# Разделение данных на признаки (X) и целевую переменную (y)
X = new_df.drop('SalePrice', axis=1)
y = new_df['SalePrice']

# Разделение данных на обучающий и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)

# Обучение модели случайного леса
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
# Предсказание на тестовом наборе
y_pred = model.predict(X_test)
# Оценка качества модели
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)
test_pred = model.predict(new_df_test)
df_price_right = pd.read_csv("sample_submission.csv")
df_price_right["PredictedPrice"] = test_pred
df_price_right["difference_price"] = abs(df_price_right["PredictedPrice"] - df_price_right["SalePrice"])/df_price_right["SalePrice"]
print(df_price_right['difference_price'].mean())
mape = mean_absolute_percentage_error(df_price_right["SalePrice"], test_pred) # Готовый метод оценки точности
print("MAPE:", mape)
df_price_right

Mean Squared Error: 1259678314.2980185
0.27697677757004857
MAPE: 0.27697677757004857

        Id      SalePrice  PredictedPrice  difference_price
0     1461  169277.052498   125190.664683          0.260439
1     1462  187758.393989   165429.560000          0.118923
2     1463  183583.683570   130767.000000          0.287698
3     1464  179317.477511   150531.000000          0.160534
4     1465  150730.079977   230979.760000          0.532407
...    ...            ...             ...               ...
1454  2915  167081.220949   100130.000000          0.400711
1455  2916  164788.778231   100130.000000          0.392374
1456  2917  219222.423400   133753.333333          0.389874
1457  2918  184924.279659   123283.500000          0.333330
1458  2919  187741.866657   203233.000000          0.082513

[1459 rows x 4 columns]

In [4]:
from sklearn.linear_model import LinearRegression
# Обучение модели линейной регрессии
model = LinearRegression()
model.fit(X_train, y_train)
# Предсказание на тестовом наборе
y_pred = model.predict(X_test)
# Оценка качества модели
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)
test_pred = model.predict(new_df_test)
df_price_right = pd.read_csv("sample_submission.csv")
df_price_right["PredictedPrice"] = test_pred
df_price_right["difference_price"] = abs(df_price_right["PredictedPrice"] - df_price_right["SalePrice"])/df_price_right["SalePrice"]
print(df_price_right['difference_price'].mean())
df_price_right

Mean Squared Error: 1296900548.7734756
0.2690323624288744

        Id      SalePrice  PredictedPrice  difference_price
0     1461  169277.052498   110694.501957          0.346075
1     1462  187758.393989   164482.684322          0.123966
2     1463  183583.683570   151934.140611          0.172398
3     1464  179317.477511   179954.581498          0.003553
4     1465  150730.079977   220579.827540          0.463409
...    ...            ...             ...               ...
1454  2915  167081.220949    92294.768041          0.447605
1455  2916  164788.778231    92294.768041          0.439921
1456  2917  219222.423400   129148.255679          0.410880
1457  2918  184924.279659   114857.848833          0.378893
1458  2919  187741.866657   231661.090425          0.233934

[1459 rows x 4 columns]

In [5]:
from sklearn.svm import SVR
# Обучение модели методом опорных векторов
model = SVR(kernel='rbf')
model.fit(X_train, y_train)
# Предсказание на тестовом наборе
y_pred = model.predict(X_test)
# Оценка качества модели
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)
test_pred = model.predict(new_df_test)
df_price_right = pd.read_csv("sample_submission.csv")
df_price_right["PredictedPrice"] = test_pred
df_price_right["difference_price"] = abs(df_price_right["PredictedPrice"] - df_price_right["SalePrice"])/df_price_right["SalePrice"]
print(df_price_right['difference_price'].mean())
df_price_right

Mean Squared Error: 4771907987.461799
0.0953121351169724

        Id      SalePrice  PredictedPrice  difference_price
0     1461  169277.052498   163725.660542          0.032795
1     1462  187758.393989   163753.002259          0.127853
2     1463  183583.683570   163777.229517          0.107888
3     1464  179317.477511   163775.269695          0.086674
4     1465  150730.079977   163749.166709          0.086374
...    ...            ...             ...               ...
1454  2915  167081.220949   163735.879643          0.020022
1455  2916  164788.778231   163735.879643          0.006389
1456  2917  219222.423400   163744.937092          0.253065
1457  2918  184924.279659   163729.000138          0.114616
1458  2919  187741.866657   163800.988906          0.127520

[1459 rows x 4 columns]